import { jsPDF } from "jspdf";

// Helper to draw clean document header
function drawHeader(doc: jsPDF, title: string, businessName: string, sub?: string) {
  // Brand primary color (purple #632a73)
  doc.setFillColor(99, 42, 115);
  doc.rect(0, 0, 210, 32, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text("Sweet Tooth", 15, 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(230, 220, 240);
  doc.text("AI for home bakers", 15, 24);

  // Document Type / Date
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text(title.toUpperCase(), 200, 16, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${businessName} · ${sub || new Date().toLocaleDateString()}`, 200, 24, { align: "right" });

  doc.setTextColor(36, 22, 41); // Reset default text color
}

// Helper to draw page footer
function drawFooter(doc: jsPDF, pageNumber: number) {
  doc.setDrawColor(223, 209, 196);
  doc.line(15, 280, 195, 280);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(116, 104, 118);
  doc.text("Generated by Sweet Tooth Baker Dashboard", 15, 285);
  doc.text(`Page ${pageNumber}`, 195, 285, { align: "right" });
}

export function exportAnalyticsPDF(
  analytics: any,
  weeklyReport: any,
  feedbackStats: any,
  chartData: any[],
  sourceData: any[],
  period: string,
  businessName: string
) {
  const doc = new jsPDF();
  let y = 45;
  let page = 1;

  drawHeader(doc, "Performance Report", businessName, `Period: ${period.toUpperCase()}`);
  drawFooter(doc, page);

  // Key Metrics Grid
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Overview Summary", 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Metric", 15, y);
  doc.text("Value", 120, y);
  y += 3;
  doc.line(15, y, 195, y);
  y += 6;

  const metrics = [
    { label: "Total Revenue", val: `PKR ${(analytics?.totalRevenue ?? 0).toLocaleString()}` },
    { label: "Total Orders", val: String(analytics?.totalOrders ?? 0) },
    { label: "Average Order Value", val: `PKR ${(analytics?.avgOrderValue ?? 0).toLocaleString()}` },
    { label: "New Customers", val: String(analytics?.newCustomers ?? 0) },
    { label: "Repeat Customers", val: String(analytics?.repeatCustomers ?? 0) },
  ];

  doc.setFont("helvetica", "normal");
  metrics.forEach((m) => {
    doc.text(m.label, 15, y);
    doc.text(m.val, 120, y);
    y += 7;
  });

  y += 5;

  // Weekly performance stats if present
  if (weeklyReport) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Weekly Success Metrics", 15, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    const weekly = [
      { label: "Weekly Orders", val: String(weeklyReport.ordersCount ?? 0) },
      { label: "Repeat Buyers", val: String(weeklyReport.repeatBuyersCount ?? 0) },
      { label: "Assistant Avg Response", val: `${weeklyReport.avgResponseTimeSec ?? 0} seconds` },
      { label: "Unverified Payment Flags", val: String(weeklyReport.failedPaymentReviewsCount ?? 0) },
    ];

    weekly.forEach((w) => {
      doc.text(w.label, 15, y);
      doc.text(w.val, 120, y);
      y += 7;
    });

    y += 5;
  }

  // Service Feedback stats if present
  if (feedbackStats) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Service Quality & Feedback", 15, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    const fb = [
      { label: "Delivered Orders Evaluated", val: String(feedbackStats.deliveredCount ?? 0) },
      { label: "Feedback Received", val: String(feedbackStats.feedbackReceived ?? 0) },
      { label: "Feedback Response Rate", val: feedbackStats.satisfactionRate ? `${feedbackStats.satisfactionRate}%` : "N/A" },
      { label: "Happy Customers ('Loved it!')", val: String(feedbackStats.lovedIt ?? 0) },
      { label: "Average Ratings ('Okay')", val: String(feedbackStats.okay ?? 0) },
      { label: "Negative Reports ('Had issue')", val: String(feedbackStats.hadIssue ?? 0) },
    ];

    fb.forEach((f) => {
      doc.text(f.label, 15, y);
      doc.text(f.val, 120, y);
      y += 7;
    });

    y += 5;
  }

  // Top Products Table (Move to page 2 if needed)
  if (analytics?.topProducts && analytics.topProducts.length > 0) {
    if (y > 180) {
      doc.addPage();
      page++;
      y = 45;
      drawHeader(doc, "Performance Report", businessName, `Period: ${period.toUpperCase()}`);
      drawFooter(doc, page);
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Top Selling Products", 15, y);
    y += 8;

    doc.setFontSize(10);
    doc.text("Product Name", 15, y);
    doc.text("Orders", 120, y);
    doc.text("Revenue", 160, y);
    y += 3;
    doc.line(15, y, 195, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    analytics.topProducts.slice(0, 10).forEach((p: any) => {
      doc.text(p.name || "Unknown Product", 15, y);
      doc.text(String(p.ordersCount ?? 0), 120, y);
      doc.text(`PKR ${(p.revenuePkr ?? 0).toLocaleString()}`, 160, y);
      y += 7;
    });
  }

  doc.save(`monthly-performance-${period}.pdf`);
}

export function exportCustomersPDF(customers: any[], businessName: string) {
  const doc = new jsPDF();
  let y = 45;
  let page = 1;

  drawHeader(doc, "Customer Directory", businessName, `Total: ${customers.length}`);
  drawFooter(doc, page);

  // Table Headers
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Customer Name", 15, y);
  doc.text("WhatsApp Number", 75, y);
  doc.text("Preferred Area", 125, y);
  doc.text("Orders", 165, y);
  doc.text("Total Spent", 180, y);
  
  y += 3;
  doc.line(15, y, 195, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  customers.forEach((c) => {
    if (y > 265) {
      doc.addPage();
      page++;
      y = 45;
      drawHeader(doc, "Customer Directory", businessName, `Total: ${customers.length}`);
      drawFooter(doc, page);

      doc.setFont("helvetica", "bold");
      doc.text("Customer Name", 15, y);
      doc.text("WhatsApp Number", 75, y);
      doc.text("Preferred Area", 125, y);
      doc.text("Orders", 165, y);
      doc.text("Total Spent", 180, y);
      
      y += 3;
      doc.line(15, y, 195, y);
      y += 6;
      doc.setFont("helvetica", "normal");
    }

    doc.text(c.name || "Guest Buyer", 15, y);
    doc.text(c.whatsappNumber || "N/A", 75, y);
    doc.text(c.preferredArea || "N/A", 125, y);
    doc.text(String(c.totalOrders ?? 0), 165, y);
    doc.text(`Rs. ${(c.totalSpentPkr ?? 0).toLocaleString()}`, 180, y);
    y += 8;
  });

  doc.save("customer-directory.pdf");
}

export function exportKhataLedgerPDF(khataAnalytics: any, ledgerEntries: any[], businessName: string) {
  const doc = new jsPDF();
  let y = 45;
  let page = 1;

  drawHeader(doc, "General Ledger Report", businessName, khataAnalytics?.label || "Statement");
  drawFooter(doc, page);

  // Profitability metrics section
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Profitability Audit Summary", 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.text("Category", 15, y);
  doc.text("Financial Record", 120, y);
  y += 3;
  doc.line(15, y, 195, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  const records = [
    { label: "Gross Sales Revenue", val: `PKR ${(khataAnalytics?.revenue ?? 0).toLocaleString()}` },
    { label: "Completed Orders Count", val: String(khataAnalytics?.deliveredOrders ?? 0) },
    { label: "Estimated Product COGS (Recipes)", val: `PKR ${(khataAnalytics?.estimatedCogsFromRecipes ?? 0).toLocaleString()}` },
    { label: "Manual Operating Expenses", val: `PKR ${(khataAnalytics?.manualExpenses ?? 0).toLocaleString()}` },
    { label: "Bakers Delivery Cost Paid", val: `PKR ${(khataAnalytics?.deliveryCosts ?? 0).toLocaleString()}` },
    { label: "Estimated Net Profit", val: `PKR ${(khataAnalytics?.netProfitAfterCogs ?? 0).toLocaleString()}` },
  ];

  records.forEach((r) => {
    doc.text(r.label, 15, y);
    doc.text(r.val, 120, y);
    y += 7;
  });

  y += 10;

  // Ledger entries table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Expense Ledger Log", 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.text("Date", 15, y);
  doc.text("Type", 40, y);
  doc.text("Category", 75, y);
  doc.text("Description", 115, y);
  doc.text("Amount", 175, y);
  y += 3;
  doc.line(15, y, 195, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  ledgerEntries.forEach((e) => {
    if (y > 265) {
      doc.addPage();
      page++;
      y = 45;
      drawHeader(doc, "General Ledger Report", businessName, khataAnalytics?.label || "Statement");
      drawFooter(doc, page);

      doc.setFont("helvetica", "bold");
      doc.text("Date", 15, y);
      doc.text("Type", 40, y);
      doc.text("Category", 75, y);
      doc.text("Description", 115, y);
      doc.text("Amount", 175, y);
      y += 3;
      doc.line(15, y, 195, y);
      y += 6;
      doc.setFont("helvetica", "normal");
    }

    doc.text(e.entryDate || "N/A", 15, y);
    doc.text(e.type?.replace("_", " ") || "expense", 40, y);
    doc.text(e.category || "general", 75, y);
    
    // Truncate description if too long
    const descText = e.description ? (e.description.length > 28 ? e.description.slice(0, 26) + ".." : e.description) : "";
    doc.text(descText, 115, y);
    
    doc.text(`Rs. ${(e.amountPkr ?? 0).toLocaleString()}`, 175, y);
    y += 8;
  });

  doc.save("khata-ledger-statement.pdf");
}

export function exportOrdersPDF(orders: any[], businessName: string) {
  const doc = new jsPDF();
  let y = 45;
  let page = 1;

  drawHeader(doc, "Orders Log", businessName, `Total Active: ${orders.length}`);
  drawFooter(doc, page);

  // Table Headers
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("ID", 15, y);
  doc.text("Customer", 28, y);
  doc.text("Delivery Date", 70, y);
  doc.text("Status", 100, y);
  doc.text("Items Summary", 130, y);
  doc.text("Total Price", 180, y);
  
  y += 3;
  doc.line(15, y, 195, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  orders.forEach((o) => {
    if (y > 265) {
      doc.addPage();
      page++;
      y = 45;
      drawHeader(doc, "Orders Log", businessName, `Total Active: ${orders.length}`);
      drawFooter(doc, page);

      doc.setFont("helvetica", "bold");
      doc.text("ID", 15, y);
      doc.text("Customer", 28, y);
      doc.text("Delivery Date", 70, y);
      doc.text("Status", 100, y);
      doc.text("Items Summary", 130, y);
      doc.text("Total Price", 180, y);
      
      y += 3;
      doc.line(15, y, 195, y);
      y += 6;
      doc.setFont("helvetica", "normal");
    }

    doc.text(String(o.id), 15, y);
    
    const customer = o.buyerName ? (o.buyerName.length > 15 ? o.buyerName.slice(0, 13) + ".." : o.buyerName) : "Guest";
    doc.text(customer, 28, y);
    doc.text(o.deliveryDate || "N/A", 70, y);
    doc.text(o.status || "new", 100, y);
    
    // Items summary
    const summary = o.items
      ?.map((item: any) => `${item.productName} x${item.quantity}`)
      .join(", ") || o.productName || "Custom Order";
    const summaryText = summary.length > 24 ? summary.slice(0, 22) + ".." : summary;
    doc.text(summaryText, 130, y);
    
    doc.text(`Rs. ${(o.totalPkr ?? 0).toLocaleString()}`, 180, y);
    y += 8;
  });

  doc.save("bakery-orders-log.pdf");
}
